sudo: false
language: cpp
notifications:
  email: false
stages: 
  - Test
  - Osx-binutils
  - Osx-pass-1
  - Osx-pass-2
jobs:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - bsdtar
            - gperf
            - texinfo
            - help2man
            - gcc-multilib
            - g++-multilib
      before_install:
        # unset is needed for libhal
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
        - echo With-osx $WITH_OSX
        - cd $TRAVIS_BUILD_DIR
        - wget -c http://ftp.gnu.org/gnu/automake/automake-1.15.tar.xz; tar xf automake-1.15.tar.xz; rm automake-1.15.tar.xz
        - cd automake-1.15; ./configure -q --prefix=/usr && make V=0; sudo make V=0 install; cd ..; rm -fR automake-1.15
      #before_script: # global
      script:
        - DEPLOY_FILE=Linux-64-xtensa-lx106-elf.tar.gz
        - if [ ! -d dist ] || [ ! -f dist/$DEPLOY_FILE ]; then make; else echo nothing to do; fi
      #after_script: # global
      before_cache: # caching is after the script
        #- rm -fR src/gmp* src/mpfr* src/mpc* src/binutils*
      cache: ###false
        directories:
          - xtensa-lx106-elf/
          - dist/
    - stage: Osx-binutils
      os: osx
      osx_image: xcode8.3
      before_install:
        - test -n $CC  && unset CC
        - test -n $CXX && unset CXX
        - cd $TRAVIS_BUILD_DIR
      #before_script: # global
      script:
        - rm -f math_libs/.installed-*
        - rm -f xtensa-lx106-elf/.installed-*
        - DEPLOY_FILE=MacOS-64-xtensa-lx106-elf.tar.gz
        - if [ ! -d dist ] || [ ! -f dist/$DEPLOY_FILE ]; then make build-binutils; make get-gcc; fi
      #after_script: # global
      before_cache: # caching is after the script
        - rm -fR src/gmp* src/mpfr* src/mpc* src/binutils*
      cache: ###false
        timeout: 2000
        directories:
          - math_libs/
          - src/gcc-7.2.0/
          - xtensa-lx106-elf/
          - dist/
    - stage: Osx-pass-1
      os: osx
      osx_image: xcode8.3
      #before_install: # global
      script:
        - DEPLOY_FILE=MacOS-64-xtensa-lx106-elf.tar.gz
        - if [ ! -d dist ] || [ ! -f dist/$DEPLOY_FILE ]; then make build-gcc-pass-1; else echo nothing to do; fi
      cache: ###false
        timeout: 2000
        directories:
          - math_libs/
          - src/gcc-7.2.0/
          - xtensa-lx106-elf/
          - dist/
    - stage: Osx-pass-2
      os: osx
      osx_image: xcode8.3
      #before_install: # global
      #before_script:  # global
      script:
        - DEPLOY_FILE=MacOS-64-xtensa-lx106-elf.tar.gz
        - if [ ! -d dist ] || [ ! -f dist/$DEPLOY_FILE ]; then make build-gcc-pass-2; else echo nothing to do; fi
      cache: ###false
        timeout: 2000
        directories:
          - math_libs/
          - src/gcc-7.2.0/
          - xtensa-lx106-elf/
          - dist/
before_deploy:
  - echo start deploy
  - make dist
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then DEPLOY_FILE=Linux-64-xtensa-lx106-elf.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then DEPLOY_FILE=MacOS-64-xtensa-lx106-elf.tar.gz; fi
deploy:
      provider: releases
      api_key: $DeployToken
      overwrite: true
      file_glob: true
      file: dist/$DEPLOY_FILE
      skip_cleanup: true
      on:
        branches:
        only:
        - master
        - /v\d+\.\d+[a-z]/
        repo: Juppit/esp-new-sdk
        tags: true
      script:
        - make dist
after_deploy:
  - echo deploy end
  #- rm -fR xtensa-lx106-elf
  - ls -ladR
before_script: # 
  - cd $TRAVIS_BUILD_DIR
  - ls -l
  - if [ -d src ]; then ls -l src; fi
  - if [ -d dist ]; then ls -l dist; fi
  - if [ -d xtensa-lx106-elf ]; then ls -la xtensa-lx106-elf; fi
after_script:  # 
  - cd $TRAVIS_BUILD_DIR
  - ls -l
  - if [ -d src ]; then ls -l src; fi
  - if [ -d dist ]; then ls -l dist; fi
  - if [ -d xtensa-lx106-elf ]; then ls -la xtensa-lx106-elf; fi
  - if [ -d xtensa-lx106-elf/bin ]; then ls -la xtensa-lx106-elf/bin; fi
